name: "Build"
run-name: "[Fundraising] .NET Build by ${{github.actor}}"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build .NET Applications
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Build Timestamp
        run: echo "BUILD_TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build FundRaisingApp
        run: dotnet publish "FundRaisingApp/FundRaisingApp.csproj" -c Release -o release/ABDrivingSchool

      - name: Ensure Target Directory Exists & Cleanup Old Builds
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            powershell -Command "if (!(Test-Path 'C:/fundraising')) { New-Item -ItemType Directory -Path 'C:/fundraising' -Force }; Get-ChildItem -Path 'C:/fundraising' -Directory | Sort-Object CreationTime -Descending | Select-Object -Skip 5 | Remove-Item -Recurse -Force"


      - name: Upload Artifacts to Windows Server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "release/FundRaisingApp"
          target: "C:/fundraising"
