name: "Build"
run-name: "[Fundraising] .NET Build by ${{github.actor}}"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build .NET Applications
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
      - name: Restore Dependencies
        run: dotnet restore "FundRaisingApp/FundRaisingApp.csproj"

      - name: Build Project
        run: dotnet build "FundRaisingApp/FundRaisingApp.csproj" -c Release

      - name: Publish FundRaisingApp
        run: dotnet publish "FundRaisingApp/FundRaisingApp.csproj" -c Release -o release/FundRaisingApp

      - name: Upload Artifacts to Windows Server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "release/FundRaisingApp"
          target: "C:/fundrasing"
